---
version: '3.4'

services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    env_file:
    - env.list
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    labels:
      org.label-schema.group: "monitoring"

volumes:
  grafana_data:

